### ISSUE TITLE
Issue with navigation on Joomla 3.4.3

### ISSUE THREAD

**Issue by yiotaz** [JPhMaat/Availcal#1]
Hello,

I have installed the component and plugin in a Joomla 3.4.3 site with K2. I use the plugin to load the 3month calendar in a K2 item. I cannot get the navigation to work, though. I get the following error every time I click on the previous/next month.

"NetworkError: 404 View not found [name...m, update, availcalView - .../index.php?option=com_availcal&format=update&id=booked&month=8&year=2015&week_firstday=0&firstlast=1&type=plugin3&wnbrdisplay=0"

Do you know how can I solve this?

Also, can each entry of the darkperiod have the same name in order to fetch multiple periods in the calendar?

Thank you in advance,
Yiota Ziaggou

**Comment by JPhMaat** [comment]
Hi Yiota,

The calendar uses jQuery function .load to get the next values.(
.load('index.php?option=.....' ) Jquery translate is to a network call
http://localhost/joomla3/index.php?option=.... (this on my test system, in
a life system this would be something like
www.domainname.com/index.php?option=...)

I have no experience with K2 at all. But from the error message I see that
www.domainname.com is replace by " name...m, update, availcalView - ..."
Try to find where this replacement is done.

On your second question: yes darkperiods may have the same name but with
different dates.

Regards,

Jan

2015-07-13 18:37 GMT+02:00 Yiota Ziaggou notifications@github.com:

**Comment by yiotaz** [comment]
When the plugin is used to fetch the calendar inside an article, the url of the article is like

http://mydomain/category-name/item/id-articlename

When you click on the next/previous btn the url 

index.php?option=com_availcal&format=update&id=booked&month=6&year=2015&week_firstday=0&firstlast=1&type=plugin3&wnbrdisplay=0"

attaches to the http://mydomain/category-name/item which is wrong.

When the plugin is used you should not use the page's url to construct the calendar url. You should use the baseURL instead. 

When I changed that in the plugin, the navigation worked fine.

I used this -> http://mydomain/index.php?option=com_availcal&format=update&id=booked&month=6&year=2015&week_firstday=0&firstlast=1&type=plugin3&wnbrdisplay=0"

instead of this -> http://mydomain/category-name/item/index.php?option=com_availcal&format=update&id=booked&month=6&year=2015&week_firstday=0&firstlast=1&type=plugin3&wnbrdisplay=0"

Maybe this works differently in a joomla article but in a K2 article you need to make the change above in order to work.

Thank you.

**Comment by JPhMaat** [comment]
Hi Yiota,

It is for me not clear where you changed the url. Please give me the
linenumber and code.

I will include your update and release it.

Thanks,

Jan

2015-07-14 10:35 GMT+02:00 Yiota Ziaggou notifications@github.com:

**Comment by yiotaz** [comment]
On the plugin file, availcal.php and in lines, 374, 382, where the .load() is used and in lines 401, 417 where the get() is used I have added the JURI::base() right before "index.php...." as below

$('#result0$y').load('".JURI::base()."index.php?option=com_availcal&format=update&id=' + id + '&month=' + monthmin + '&year=' + year + '&week_firstday=' + week_firstday + '&firstlast=' + firstlast + '&type=plugin' + '&wnbrdisplay='+ wnbrdisplay,

**Comment by JPhMaat** [comment]
Hallo Yiota,

Thanks,

The update is released in version 07_0_3

Jan

2015-07-14 12:53 GMT+02:00 Yiota Ziaggou notifications@github.com:

**Comment by yiotaz** [comment]
I'm glad I have helped :)
