### ISSUE TITLE
How to disable date older then current date

### ISSUE THREAD

**Issue by nirmaladdon** [JPhMaat/Availcal#2]
i would like disable date till currant date like jquery calendar.how can i do like this

**Comment by JPhMaat** [comment]
The joomla built in calendar function  is used. I am not aware  this
function has any option  to disable dates in the past.

2015-07-15 7:26 GMT+02:00 nirmaladdon notifications@github.com:

**Comment by nirmaladdon** [comment]
closed due to disable date older then current date functionality is not available
