### ISSUE TITLE
publish vs unpublish ?

### ISSUE THREAD

**Issue by AlainRnet** [JPhMaat/Availcal#5]
Hi!
I discover your simple and excellent component. Great work, thank you very much.

Is it possible - and easy to develop - to add the possibility to publish and unpublish the Darkperiods ?

Thank you in advance for your answer.
Best regards,
AlainR

**Comment by JPhMaat** [comment]
Hi,

In case you only use the full busy status you may use the party status as unpublished.
In the plugin and/or module settings you must add on the tab Custom CSS- Enter CSS rules the following text: .cal_part { background-color:#fff;}

With this setting the darkperiods with the busy status “partly” are not shown.

Regards,

Jan

**Comment by AlainRnet** [comment]
Thank you for your answer. But I cannot do that because I have 2 differents objects to display on calendar, so I use full for one and party for the second.
Any other idea ?
Many thanks again.
Best regards,
AlainR

**Comment by AlainRnet** [comment]
Sorry, I think you're right, I can do as you suggest.
Many thanks.
AlainR

**Comment by AlainRnet** [comment]
Thank you again.
Finally the following CSS code is required:
.cal_part{background-color:transparent}
.cal_part.display_part, .display_part{display:none}
