### ISSUE TITLE
filter in back-end

### ISSUE THREAD

**Issue by AlainRnet** [JPhMaat/Availcal#7]
Hi!
I would like to filter records but it does not. Like the "remove" button does not clear the filter field.
I try to change something in default_items.php file, but it doesn't work.

Thanks in advance for help.
Best regards.

**Comment by JPhMaat** [comment]
I solved it in the version 07_0_4.

It filter only the name field.

regards,

Jan

**Comment by AlainRnet** [comment]
Thank you a lot!
I customize your component and, with Fabrik, it's beautiful.
Best regards.
